openapi : 3.0.0
info : 
  title : Social App API
  description : Our First Social App - Pavaman
  version : 1.0.1

servers:
  - url: http://localhost:4000/api/v1/
    description: localhost version of our app
  - url: http://localhost:4000/api/v1/
    description: This is just a dummy API URL, it doens't work

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    BearerAuth:
      type: http
      scheme: bearer

paths: 
  /instagram : 
    get : 
      summary : return username, followers and follows
      responses: 
        '200' : # status code
          description: returns an object
          content : 
            application/jsom : 
              schema : 
                type : object
                properties : 
                  username : 
                    type : string
                  followers : 
                    type : string
                  follows : 
                    type : string
  /{token}:                  
    get : 
      summary : returns whatever is there in parameter
      parameters:
        - name : token
          default : 5
          in : path
          schema : 
            type : string
      responses: 
        '200' : # status code
          description: returns an object
          content : 
            application/jsom : 
              schema : 
                type : object
                properties : 
                  params : 
                    type : string
